services:

  karmabot:
    build:
      context: .
      dockerfile: Dockerfile

    image: target/karmabot:local
    ports:
      - 5000:5000
    volumes:
      - karmabot_data:/app/data
    environment:
      - FAKE_SLACK=True
      - RUNTIME_LOG_LEVEL=debug
      - LOG_LEVEL=DEBUG
      - SQLITE_PATH=/app/data/karmabot.db
      - OTEL_SERVICE_NAME=karmabot
      - VERIFICATION_TOKEN=v_token
      - ACCESS_T123456=oauth_token
      - BOT_T123456=b_token

volumes:
  karmabot_data:
